name: comp735
favicon: null
layout_spectrum: 0.9805299735162407
typography_spectrum: 0.11247979803010821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1495646140538156
  lightness: 0.4425450274720788
  saturation: 0.9544217751827091
  rhythmicContrast: 0.07523752632550895
purpose: []
